# Generated by Django 5.0.6 on 2024-06-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_remove_message_receiver_message_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='solar_time_stamp',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
